# Generated by Django 4.1.1 on 2022-11-20 16:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0004_document'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Document',
        ),
    ]
