# Generated by Django 4.1.1 on 2022-11-20 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0005_delete_document'),
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document', models.FileField(upload_to='documents/%Y/%m/%d/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
